services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: sso-keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HOSTNAME=localhost
      - KC_HOSTNAME_PORT=8080
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
    depends_on:
      - postgres
    networks:
      - sso-network

  postgres:
    image: postgres:15-alpine
    container_name: sso-postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sso-network

  app1-saml-backend:
    build:
      context: ./app1-saml
      dockerfile: Dockerfile
    container_name: sso-app1-saml-backend
    ports:
      - "3000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - SECRET_KEY=dev-secret-key-change-in-production
      - SAML_IDP_ENTITY_ID=http://localhost:8080/realms/sso-poc
      - SAML_IDP_SSO_URL=http://localhost:8080/realms/sso-poc/protocol/saml
      - SAML_IDP_SLO_URL=http://localhost:8080/realms/sso-poc/protocol/saml
      - SAML_SP_ENTITY_ID=http://localhost:3000
      - SAML_SP_CALLBACK_URL=http://localhost:3000/saml/callback
    depends_on:
      - keycloak
    networks:
      - sso-network
    volumes:
      - ./app1-saml/backend:/app

  app1-saml-frontend:
    build:
      context: ./app1-saml/frontend
      dockerfile: Dockerfile
    container_name: sso-app1-saml-frontend
    ports:
      - "3001:80"
    depends_on:
      - app1-saml-backend
    networks:
      - sso-network

  app2-oidc-backend:
    build:
      context: ./app2-oidc
      dockerfile: Dockerfile
    container_name: sso-app2-oidc-backend
    ports:
      - "4000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - SECRET_KEY=dev-secret-key-change-in-production
      - OIDC_CLIENT_ID=app2-oidc
      - OIDC_CLIENT_SECRET=secret
      - OIDC_ISSUER=http://keycloak:8080/realms/sso-poc
      - OIDC_ISSUER_PUBLIC=http://localhost:8080/realms/sso-poc
      - OIDC_REDIRECT_URI=http://localhost:4000/oidc/callback
    depends_on:
      - keycloak
    networks:
      - sso-network
    volumes:
      - ./app2-oidc/backend:/app

  app2-oidc-frontend:
    build:
      context: ./app2-oidc/frontend
      dockerfile: Dockerfile
    container_name: sso-app2-oidc-frontend
    ports:
      - "4001:80"
    depends_on:
      - app2-oidc-backend
    networks:
      - sso-network

volumes:
  postgres_data:

networks:
  sso-network:
    driver: bridge